//Generated by 24HRS
package Servlets;


import Models.Delivary;
import Controllers.DelivaryController;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;


@WebServlet(name = "DelivaryServlet", urlPatterns = {"/DelivaryServlet"})


public class DelivaryServlet extends HttpServlet {

	protected void processRequest(HttpServletRequest request, HttpServletResponse response)
		throws ServletException, IOException {
		response.setContentType("text/html;charset=UTF-8");
		try (PrintWriter out = response.getWriter()) {

		String action = request.getParameter("action");
		String pattern = "yyyy/MM/dd - HH:mm:ss";
		SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);
		String current_date = simpleDateFormat.format(new Date());

		if (action.equals("insert")) {
			int invoice_id = Integer.parseInt(request.getParameter("invoice_id"));
			int emp_id = Integer.parseInt(request.getParameter("emp_id"));
			String address = request.getParameter("address");
			String cus_contact = request.getParameter("cus_contact");
			String status = request.getParameter("status");
			Delivary obj = new Delivary();
			obj.setInvoice_id(invoice_id);
			obj.setEmp_id(emp_id);
			obj.setAddress(address);
			obj.setCus_contact(cus_contact);
			obj.setStatus(status);
			obj.setDate_time(current_date);
			try {
				DelivaryController.getInstance().Save(obj);
				response.getWriter().println("Saved!");
			} catch (Exception ex) {
				//error
			}
		} else if (action.equals("update")) {
			int delivary_id = Integer.parseInt(request.getParameter("delivary_id"));
			int invoice_id = Integer.parseInt(request.getParameter("invoice_id"));
			int emp_id = Integer.parseInt(request.getParameter("emp_id"));
			String address = request.getParameter("address");
			String cus_contact = request.getParameter("cus_contact");
			String status = request.getParameter("status");
			Delivary obj = new Delivary();
			obj.setDelivary_id(delivary_id);
			obj.setInvoice_id(invoice_id);
			obj.setEmp_id(emp_id);
			obj.setAddress(address);
			obj.setCus_contact(cus_contact);
			obj.setStatus(status);
			obj.setDate_time(current_date);
			try {
				DelivaryController.getInstance().Update(obj);
				response.getWriter().println("Updated!");
			} catch (Exception ex) {
				//error
			}

		} else if (action.equals("delete")) {
			int delivary_id = Integer.parseInt(request.getParameter("delivary_id"));
			Delivary obj = new Delivary();
			obj.setDelivary_id(delivary_id);
			try {
				DelivaryController.getInstance().Delete(obj);
				response.getWriter().println("Updated!");
			} catch (Exception ex) {
				//error
			}
		} else if (action.equals("serch")) {
			try {
				List<Delivary> list = new ArrayList<>();
				List stringList = new ArrayList<>();

				list = DelivaryController.getInstance().SearchAll();
				for (int i = 0; i < list.size(); i++) {
					String s = list.get(i).getDelivary_id() + "_"+list.get(i).getInvoice_id() + "_"+list.get(i).getEmp_id() + "_"+list.get(i).getAddress() + "_"+list.get(i).getCus_contact() + "_"+list.get(i).getStatus() + "_"+list.get(i).getDate_time() + "_";
					stringList.add(s);
				}
			String b = String.join("~", stringList);
			response.getWriter().println(b);
			} catch (Exception ex) {
				//Error
			}

		}
		}
	}

@Override
protected void doGet(HttpServletRequest request, HttpServletResponse response)
	throws ServletException, IOException {
		processRequest(request, response);
}

@Override
protected void doPost(HttpServletRequest request, HttpServletResponse response)
	throws ServletException, IOException {
		processRequest(request, response);
}

@Override
public String getServletInfo() {
	return "Short description";
}
}