//Generated by 24HRS
package Servlets;


import Models.Employee;
import Controllers.EmployeeController;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;


@WebServlet(name = "EmployeeServlet", urlPatterns = {"/EmployeeServlet"})


public class EmployeeServlet extends HttpServlet {

	protected void processRequest(HttpServletRequest request, HttpServletResponse response)
		throws ServletException, IOException {
		response.setContentType("text/html;charset=UTF-8");
		try (PrintWriter out = response.getWriter()) {

		String action = request.getParameter("action");
		String pattern = "yyyy/MM/dd - HH:mm:ss";
		SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);
		String current_date = simpleDateFormat.format(new Date());

		if (action.equals("insert")) {
			String full_name = request.getParameter("full_name");
			String address = request.getParameter("address");
			String email = request.getParameter("email");
			String contact_number = request.getParameter("contact_number");
			String designation = request.getParameter("designation");
			Employee obj = new Employee();
			obj.setFull_name(full_name);
			obj.setAddress(address);
			obj.setEmail(email);
			obj.setContact_number(contact_number);
			obj.setDesignation(designation);
			obj.setDate_time(current_date);
			try {
				EmployeeController.getInstance().Save(obj);
				response.getWriter().println("Saved!");
			} catch (Exception ex) {
				//error
			}
		} else if (action.equals("update")) {
			int emp_id = Integer.parseInt(request.getParameter("emp_id"));
			String full_name = request.getParameter("full_name");
			String address = request.getParameter("address");
			String email = request.getParameter("email");
			String contact_number = request.getParameter("contact_number");
			String designation = request.getParameter("designation");
			Employee obj = new Employee();
			obj.setEmp_id(emp_id);
			obj.setFull_name(full_name);
			obj.setAddress(address);
			obj.setEmail(email);
			obj.setContact_number(contact_number);
			obj.setDesignation(designation);
			obj.setDate_time(current_date);
			try {
				EmployeeController.getInstance().Update(obj);
				response.getWriter().println("Updated!");
			} catch (Exception ex) {
				//error
			}

		} else if (action.equals("delete")) {
			int emp_id = Integer.parseInt(request.getParameter("emp_id"));
			Employee obj = new Employee();
			obj.setEmp_id(emp_id);
			try {
				EmployeeController.getInstance().Delete(obj);
				response.getWriter().println("Updated!");
			} catch (Exception ex) {
				//error
			}
		} else if (action.equals("serch")) {
			try {
				List<Employee> list = new ArrayList<>();
				List stringList = new ArrayList<>();

				list = EmployeeController.getInstance().SearchAll();
				for (int i = 0; i < list.size(); i++) {
					String s = list.get(i).getEmp_id() + "_"+list.get(i).getFull_name() + "_"+list.get(i).getAddress() + "_"+list.get(i).getEmail() + "_"+list.get(i).getContact_number() + "_"+list.get(i).getDesignation() + "_"+list.get(i).getDate_time() + "_";
					stringList.add(s);
				}
			String b = String.join("~", stringList);
			response.getWriter().println(b);
			} catch (Exception ex) {
				//Error
			}

		}
		}
	}

@Override
protected void doGet(HttpServletRequest request, HttpServletResponse response)
	throws ServletException, IOException {
		processRequest(request, response);
}

@Override
protected void doPost(HttpServletRequest request, HttpServletResponse response)
	throws ServletException, IOException {
		processRequest(request, response);
}

@Override
public String getServletInfo() {
	return "Short description";
}
}