//Generated by 24HRS
package Servlets;


import Models.Salary_shedule;
import Controllers.Salary_sheduleController;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;


@WebServlet(name = "Salary_sheduleServlet", urlPatterns = {"/Salary_sheduleServlet"})


public class Salary_sheduleServlet extends HttpServlet {

	protected void processRequest(HttpServletRequest request, HttpServletResponse response)
		throws ServletException, IOException {
		response.setContentType("text/html;charset=UTF-8");
		try (PrintWriter out = response.getWriter()) {

		String action = request.getParameter("action");
		String pattern = "yyyy/MM/dd - HH:mm:ss";
		SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);
		String current_date = simpleDateFormat.format(new Date());

		if (action.equals("insert")) {
			int emp_id = Integer.parseInt(request.getParameter("emp_id"));
			double basic_salary = Double.parseDouble(request.getParameter("basic_salary"));
			double ot_rate = Double.parseDouble(request.getParameter("ot_rate"));
			double bonus = Double.parseDouble(request.getParameter("bonus"));
			String date_time = request.getParameter("date_time");
			Salary_shedule obj = new Salary_shedule();
			obj.setEmp_id(emp_id);
			obj.setBasic_salary(basic_salary);
			obj.setOt_rate(ot_rate);
			obj.setBonus(bonus);
			obj.setDate_time(date_time);
			try {
				Salary_sheduleController.getInstance().Save(obj);
				response.getWriter().println("Saved!");
			} catch (Exception ex) {
				//error
			}
		} else if (action.equals("update")) {
			int salary_shedule_id = Integer.parseInt(request.getParameter("salary_shedule_id"));
			int emp_id = Integer.parseInt(request.getParameter("emp_id"));
			double basic_salary = Double.parseDouble(request.getParameter("basic_salary"));
			double ot_rate = Double.parseDouble(request.getParameter("ot_rate"));
			double bonus = Double.parseDouble(request.getParameter("bonus"));
			String date_time = request.getParameter("date_time");
			Salary_shedule obj = new Salary_shedule();
			obj.setSalary_shedule_id(salary_shedule_id);
			obj.setEmp_id(emp_id);
			obj.setBasic_salary(basic_salary);
			obj.setOt_rate(ot_rate);
			obj.setBonus(bonus);
			obj.setDate_time(date_time);
			try {
				Salary_sheduleController.getInstance().Update(obj);
				response.getWriter().println("Updated!");
			} catch (Exception ex) {
				//error
			}

		} else if (action.equals("delete")) {
			int salary_shedule_id = Integer.parseInt(request.getParameter("salary_shedule_id"));
			Salary_shedule obj = new Salary_shedule();
			obj.setSalary_shedule_id(salary_shedule_id);
			try {
				Salary_sheduleController.getInstance().Delete(obj);
				response.getWriter().println("Updated!");
			} catch (Exception ex) {
				//error
			}
		} else if (action.equals("serch")) {
			try {
				List<Salary_shedule> list = new ArrayList<>();
				List stringList = new ArrayList<>();

				list = Salary_sheduleController.getInstance().SearchAll();
				for (int i = 0; i < list.size(); i++) {
					String s = list.get(i).getSalary_shedule_id() + "_"+list.get(i).getEmp_id() + "_"+list.get(i).getBasic_salary() + "_"+list.get(i).getOt_rate() + "_"+list.get(i).getBonus() + "_"+list.get(i).getDate_time() + "_";
					stringList.add(s);
				}
			String b = String.join("~", stringList);
			response.getWriter().println(b);
			} catch (Exception ex) {
				//Error
			}

		}
		}
	}

@Override
protected void doGet(HttpServletRequest request, HttpServletResponse response)
	throws ServletException, IOException {
		processRequest(request, response);
}

@Override
protected void doPost(HttpServletRequest request, HttpServletResponse response)
	throws ServletException, IOException {
		processRequest(request, response);
}

@Override
public String getServletInfo() {
	return "Short description";
}
}