//Generated by 24HRS
package Models;


public class Customer{

	private int customer_id;
	private String name;
	private String address;
	private String contact_no;
	private String email;
	private String date_time;

public Customer(){
}

public Customer(int customer_id){
	this.customer_id = customer_id;
}
public Customer(int customer_id,String name,String address,String contact_no,String email,String date_time){
	this.customer_id = customer_id;
	this.name = name;
	this.address = address;
	this.contact_no = contact_no;
	this.email = email;
	this.date_time = date_time;
}

public int getCustomer_id(){
return customer_id;
}

public void setCustomer_id(int customer_id){
	this.customer_id = customer_id;
}

public String getName(){
return name;
}

public void setName(String name){
	this.name = name;
}

public String getAddress(){
return address;
}

public void setAddress(String address){
	this.address = address;
}

public String getContact_no(){
return contact_no;
}

public void setContact_no(String contact_no){
	this.contact_no = contact_no;
}

public String getEmail(){
return email;
}

public void setEmail(String email){
	this.email = email;
}

public String getDate_time(){
return date_time;
}

public void setDate_time(String date_time){
	this.date_time = date_time;
}

}