//Generated by 24HRS
package Models;


public class Grn{

	private int grn_id;
	private int supplier_id;
	private double total;
	private String status;
	private String date_time;

public Grn(){
}

public Grn(int grn_id){
	this.grn_id = grn_id;
}
public Grn(int grn_id,int supplier_id,double total,String status,String date_time){
	this.grn_id = grn_id;
	this.supplier_id = supplier_id;
	this.total = total;
	this.status = status;
	this.date_time = date_time;
}

public int getGrn_id(){
return grn_id;
}

public void setGrn_id(int grn_id){
	this.grn_id = grn_id;
}

public int getSupplier_id(){
return supplier_id;
}

public void setSupplier_id(int supplier_id){
	this.supplier_id = supplier_id;
}

public double getTotal(){
return total;
}

public void setTotal(double total){
	this.total = total;
}

public String getStatus(){
return status;
}

public void setStatus(String status){
	this.status = status;
}

public String getDate_time(){
return date_time;
}

public void setDate_time(String date_time){
	this.date_time = date_time;
}

}