//Generated by 24HRS
package Models;


public class Grn_details{

	private int grn_details;
	private int grn_id;
	private int item_registration_id;
	private double qty;
	private double unit_price;
	private String status;
	private String date_time;

public Grn_details(){
}

public Grn_details(int grn_details){
	this.grn_details = grn_details;
}
public Grn_details(int grn_details,int grn_id,int item_registration_id,double qty,double unit_price,String status,String date_time){
	this.grn_details = grn_details;
	this.grn_id = grn_id;
	this.item_registration_id = item_registration_id;
	this.qty = qty;
	this.unit_price = unit_price;
	this.status = status;
	this.date_time = date_time;
}

public int getGrn_details(){
return grn_details;
}

public void setGrn_details(int grn_details){
	this.grn_details = grn_details;
}

public int getGrn_id(){
return grn_id;
}

public void setGrn_id(int grn_id){
	this.grn_id = grn_id;
}

public int getItem_registration_id(){
return item_registration_id;
}

public void setItem_registration_id(int item_registration_id){
	this.item_registration_id = item_registration_id;
}

public double getQty(){
return qty;
}

public void setQty(double qty){
	this.qty = qty;
}

public double getUnit_price(){
return unit_price;
}

public void setUnit_price(double unit_price){
	this.unit_price = unit_price;
}

public String getStatus(){
return status;
}

public void setStatus(String status){
	this.status = status;
}

public String getDate_time(){
return date_time;
}

public void setDate_time(String date_time){
	this.date_time = date_time;
}

}