//Generated by 24HRS
package Models;


public class Invoice{

	private int invoice_id;
	private int customer_id;
	private double total;
	private double offer_amount;
	private String status;
	private String date_time;

public Invoice(){
}

public Invoice(int invoice_id){
	this.invoice_id = invoice_id;
}
public Invoice(int invoice_id,int customer_id,double total,double offer_amount,String status,String date_time){
	this.invoice_id = invoice_id;
	this.customer_id = customer_id;
	this.total = total;
	this.offer_amount = offer_amount;
	this.status = status;
	this.date_time = date_time;
}

public int getInvoice_id(){
return invoice_id;
}

public void setInvoice_id(int invoice_id){
	this.invoice_id = invoice_id;
}

public int getCustomer_id(){
return customer_id;
}

public void setCustomer_id(int customer_id){
	this.customer_id = customer_id;
}

public double getTotal(){
return total;
}

public void setTotal(double total){
	this.total = total;
}

public double getOffer_amount(){
return offer_amount;
}

public void setOffer_amount(double offer_amount){
	this.offer_amount = offer_amount;
}

public String getStatus(){
return status;
}

public void setStatus(String status){
	this.status = status;
}

public String getDate_time(){
return date_time;
}

public void setDate_time(String date_time){
	this.date_time = date_time;
}

}