//Generated by 24HRS
package Models;

public class Invoice_details {

    private int invoice_details_id;
    private int invoice_id;
    private int item_registration_id;
    private double qty;
    private String date_time;

    public Invoice_details() {
    }

    public Invoice_details(int invoice_details_id) {
        this.invoice_details_id = invoice_details_id;
    }

    public Invoice_details(int invoice_details_id, int invoice_id, int item_registration_id, double qty, String date_time) {
        this.invoice_details_id = invoice_details_id;
        this.invoice_id = invoice_id;
        this.item_registration_id = item_registration_id;
        this.qty = qty;
        this.date_time = date_time;
    }

    public int getInvoice_details_id() {
        return invoice_details_id;
    }

    public void setInvoice_details_id(int invoice_details_id) {
        this.invoice_details_id = invoice_details_id;
    }

    public int getInvoice_id() {
        return invoice_id;
    }

    public void setInvoice_id(int invoice_id) {
        this.invoice_id = invoice_id;
    }

    public int getItem_registration_id() {
        return item_registration_id;
    }

    public void setItem_registration_id(int item_registration_id) {
        this.item_registration_id = item_registration_id;
    }

    public double getQty() {
        return qty;
    }

    public void setQty(double qty) {
        this.qty = qty;
    }

    public String getDate_time() {
        return date_time;
    }

    public void setDate_time(String date_time) {
        this.date_time = date_time;
    }

}
