//Generated by 24HRS
package Models;


public class Item_registration{

	private int item_registration_id;
	private String name;
	private String category;
	private String description;
	private double unit_price;
	private String date_time;

public Item_registration(){
}

public Item_registration(int item_registration_id){
	this.item_registration_id = item_registration_id;
}
public Item_registration(int item_registration_id,String name,String category,String description,double unit_price,String date_time){
	this.item_registration_id = item_registration_id;
	this.name = name;
	this.category = category;
	this.description = description;
	this.unit_price = unit_price;
	this.date_time = date_time;
}

public int getItem_registration_id(){
return item_registration_id;
}

public void setItem_registration_id(int item_registration_id){
	this.item_registration_id = item_registration_id;
}

public String getName(){
return name;
}

public void setName(String name){
	this.name = name;
}

public String getCategory(){
return category;
}

public void setCategory(String category){
	this.category = category;
}

public String getDescription(){
return description;
}

public void setDescription(String description){
	this.description = description;
}

public double getUnit_price(){
return unit_price;
}

public void setUnit_price(double unit_price){
	this.unit_price = unit_price;
}

public String getDate_time(){
return date_time;
}

public void setDate_time(String date_time){
	this.date_time = date_time;
}

}