//Generated by 24HRS
package Models;


public class Stock{

	private int stock_id;
	private int item_registration_id;
	private double qty;
	private double offer_presentage;
	private String date_time;

public Stock(){
}

public Stock(int stock_id){
	this.stock_id = stock_id;
}
public Stock(int stock_id,int item_registration_id,double qty,double offer_presentage,String date_time){
	this.stock_id = stock_id;
	this.item_registration_id = item_registration_id;
	this.qty = qty;
	this.offer_presentage = offer_presentage;
	this.date_time = date_time;
}

public int getStock_id(){
return stock_id;
}

public void setStock_id(int stock_id){
	this.stock_id = stock_id;
}

public int getItem_registration_id(){
return item_registration_id;
}

public void setItem_registration_id(int item_registration_id){
	this.item_registration_id = item_registration_id;
}

public double getQty(){
return qty;
}

public void setQty(double qty){
	this.qty = qty;
}

public double getOffer_presentage(){
return offer_presentage;
}

public void setOffer_presentage(double offer_presentage){
	this.offer_presentage = offer_presentage;
}

public String getDate_time(){
return date_time;
}

public void setDate_time(String date_time){
	this.date_time = date_time;
}

}