//Generated by 24HRS
package Controllers;


import Models.Attendance;
import DataBaseConnector.Connector;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;


public class AttendanceController{

	Connector con = Connector.getInstance();

	private AttendanceController(){
	}

	private static final AttendanceController obj = new AttendanceController();

	public static AttendanceController getInstance(){
		return obj;
	}

	public void Save(Attendance data) throws Exception {
		con.getConnection();
		con.aud("INSERT INTO attendance(emp_id,month,no_of_days,no_of_ot,advance,date_time) values ('" + data.getEmp_id()+ "','" + data.getMonth()+ "','" + data.getNo_of_days()+ "','" + data.getNo_of_ot()+ "','" + data.getAdvance()+ "','" + data.getDate_time()+ "') " );
	}

	public void Update(Attendance data) throws Exception {
		con.getConnection();
		con.aud("UPDATE attendance SET emp_id  = '" + data.getEmp_id()+ "',month  = '" + data.getMonth()+ "',no_of_days  = '" + data.getNo_of_days()+ "',no_of_ot  = '" + data.getNo_of_ot()+ "',advance  = '" + data.getAdvance()+ "',date_time  = '" + data.getDate_time()+ "' WHERE attendance_id = '" + data.getAttendance_id()+ "'");
	}

	public void Delete(Attendance data) throws Exception {
		con.getConnection();
		con.aud("DELETE FROM attendance WHERE attendance_id = '" + data.getAttendance_id()+ "'");
	}

	public List<Attendance> SearchAll() throws Exception {
		List<Attendance> objList = new ArrayList<Attendance>();
		con.getConnection();
		ResultSet rset = con.srh("SELECT * FROM attendance");
		while(rset.next()){
			Attendance obj = new Attendance();
			obj.setAttendance_id(rset.getInt(1));
			obj.setEmp_id(rset.getInt(2));
			obj.setMonth(rset.getString(3));
			obj.setNo_of_days(rset.getDouble(4));
			obj.setNo_of_ot(rset.getDouble(5));
			obj.setAdvance(rset.getDouble(6));
			obj.setDate_time(rset.getString(7));
			objList.add(obj);
		}

	return objList;
	}

	public List<Attendance> Search(Attendance data) throws Exception {
		List<Attendance> objList = new ArrayList<Attendance>();
		con.getConnection();
		ResultSet rset = con.srh("SELECT * FROM attendance WHERE attendance_id = '" + data.getAttendance_id()+ "'");
		while(rset.next()){
			Attendance obj = new Attendance();
			obj.setAttendance_id(rset.getInt(1));
			obj.setEmp_id(rset.getInt(2));
			obj.setMonth(rset.getString(3));
			obj.setNo_of_days(rset.getDouble(4));
			obj.setNo_of_ot(rset.getDouble(5));
			obj.setAdvance(rset.getDouble(6));
			obj.setDate_time(rset.getString(7));
			objList.add(obj);
		}

	return objList;
	}

}