//Generated by 24HRS
package Controllers;


import Models.Delivary;
import DataBaseConnector.Connector;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;


public class DelivaryController{

	Connector con = Connector.getInstance();

	private DelivaryController(){
	}

	private static final DelivaryController obj = new DelivaryController();

	public static DelivaryController getInstance(){
		return obj;
	}

	public void Save(Delivary data) throws Exception {
		con.getConnection();
		con.aud("INSERT INTO delivary(invoice_id,emp_id,address,cus_contact,status,date_time) values ('" + data.getInvoice_id()+ "','" + data.getEmp_id()+ "','" + data.getAddress()+ "','" + data.getCus_contact()+ "','" + data.getStatus()+ "','" + data.getDate_time()+ "') " );
	}

	public void Update(Delivary data) throws Exception {
		con.getConnection();
		con.aud("UPDATE delivary SET invoice_id  = '" + data.getInvoice_id()+ "',emp_id  = '" + data.getEmp_id()+ "',address  = '" + data.getAddress()+ "',cus_contact  = '" + data.getCus_contact()+ "',status  = '" + data.getStatus()+ "',date_time  = '" + data.getDate_time()+ "' WHERE delivary_id = '" + data.getDelivary_id()+ "'");
	}

	public void Delete(Delivary data) throws Exception {
		con.getConnection();
		con.aud("DELETE FROM delivary WHERE delivary_id = '" + data.getDelivary_id()+ "'");
	}

	public List<Delivary> SearchAll() throws Exception {
		List<Delivary> objList = new ArrayList<Delivary>();
		con.getConnection();
		ResultSet rset = con.srh("SELECT * FROM delivary");
		while(rset.next()){
			Delivary obj = new Delivary();
			obj.setDelivary_id(rset.getInt(1));
			obj.setInvoice_id(rset.getInt(2));
			obj.setEmp_id(rset.getInt(3));
			obj.setAddress(rset.getString(4));
			obj.setCus_contact(rset.getString(5));
			obj.setStatus(rset.getString(6));
			obj.setDate_time(rset.getString(7));
			objList.add(obj);
		}

	return objList;
	}

	public List<Delivary> Search(Delivary data) throws Exception {
		List<Delivary> objList = new ArrayList<Delivary>();
		con.getConnection();
		ResultSet rset = con.srh("SELECT * FROM delivary WHERE delivary_id = '" + data.getDelivary_id()+ "'");
		while(rset.next()){
			Delivary obj = new Delivary();
			obj.setDelivary_id(rset.getInt(1));
			obj.setInvoice_id(rset.getInt(2));
			obj.setEmp_id(rset.getInt(3));
			obj.setAddress(rset.getString(4));
			obj.setCus_contact(rset.getString(5));
			obj.setStatus(rset.getString(6));
			obj.setDate_time(rset.getString(7));
			objList.add(obj);
		}

	return objList;
	}

}