//Generated by 24HRS
package Controllers;


import Models.Grn_details;
import DataBaseConnector.Connector;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;


public class Grn_detailsController{

	Connector con = Connector.getInstance();

	private Grn_detailsController(){
	}

	private static final Grn_detailsController obj = new Grn_detailsController();

	public static Grn_detailsController getInstance(){
		return obj;
	}

	public void Save(Grn_details data) throws Exception {
		con.getConnection();
		con.aud("INSERT INTO grn_details(grn_id,item_registration_id,qty,unit_price,status,date_time) values ('" + data.getGrn_id()+ "','" + data.getItem_registration_id()+ "','" + data.getQty()+ "','" + data.getUnit_price()+ "','" + data.getStatus()+ "','" + data.getDate_time()+ "') " );
	}

	public void Update(Grn_details data) throws Exception {
		con.getConnection();
		con.aud("UPDATE grn_details SET grn_id  = '" + data.getGrn_id()+ "',item_registration_id  = '" + data.getItem_registration_id()+ "',qty  = '" + data.getQty()+ "',unit_price  = '" + data.getUnit_price()+ "',status  = '" + data.getStatus()+ "',date_time  = '" + data.getDate_time()+ "' WHERE grn_details = '" + data.getGrn_details()+ "'");
	}

	public void Delete(Grn_details data) throws Exception {
		con.getConnection();
		con.aud("DELETE FROM grn_details WHERE grn_details = '" + data.getGrn_details()+ "'");
	}

	public List<Grn_details> SearchAll() throws Exception {
		List<Grn_details> objList = new ArrayList<Grn_details>();
		con.getConnection();
		ResultSet rset = con.srh("SELECT * FROM grn_details");
		while(rset.next()){
			Grn_details obj = new Grn_details();
			obj.setGrn_details(rset.getInt(1));
			obj.setGrn_id(rset.getInt(2));
			obj.setItem_registration_id(rset.getInt(3));
			obj.setQty(rset.getDouble(4));
			obj.setUnit_price(rset.getDouble(5));
			obj.setStatus(rset.getString(6));
			obj.setDate_time(rset.getString(7));
			objList.add(obj);
		}

	return objList;
	}

	public List<Grn_details> Search(Grn_details data) throws Exception {
		List<Grn_details> objList = new ArrayList<Grn_details>();
		con.getConnection();
		ResultSet rset = con.srh("SELECT * FROM grn_details WHERE grn_details = '" + data.getGrn_details()+ "'");
		while(rset.next()){
			Grn_details obj = new Grn_details();
			obj.setGrn_details(rset.getInt(1));
			obj.setGrn_id(rset.getInt(2));
			obj.setItem_registration_id(rset.getInt(3));
			obj.setQty(rset.getDouble(4));
			obj.setUnit_price(rset.getDouble(5));
			obj.setStatus(rset.getString(6));
			obj.setDate_time(rset.getString(7));
			objList.add(obj);
		}

	return objList;
	}

}