//Generated by 24HRS
package Controllers;


import Models.Grn;
import DataBaseConnector.Connector;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;


public class GrnController{

	Connector con = Connector.getInstance();

	private GrnController(){
	}

	private static final GrnController obj = new GrnController();

	public static GrnController getInstance(){
		return obj;
	}

	public void Save(Grn data) throws Exception {
		con.getConnection();
		con.aud("INSERT INTO grn(supplier_id,total,status,date_time) values ('" + data.getSupplier_id()+ "','" + data.getTotal()+ "','" + data.getStatus()+ "','" + data.getDate_time()+ "') " );
	}

	public void Update(Grn data) throws Exception {
		con.getConnection();
		con.aud("UPDATE grn SET supplier_id  = '" + data.getSupplier_id()+ "',total  = '" + data.getTotal()+ "',status  = '" + data.getStatus()+ "',date_time  = '" + data.getDate_time()+ "' WHERE grn_id = '" + data.getGrn_id()+ "'");
	}

	public void Delete(Grn data) throws Exception {
		con.getConnection();
		con.aud("DELETE FROM grn WHERE grn_id = '" + data.getGrn_id()+ "'");
	}

	public List<Grn> SearchAll() throws Exception {
		List<Grn> objList = new ArrayList<Grn>();
		con.getConnection();
		ResultSet rset = con.srh("SELECT * FROM grn");
		while(rset.next()){
			Grn obj = new Grn();
			obj.setGrn_id(rset.getInt(1));
			obj.setSupplier_id(rset.getInt(2));
			obj.setTotal(rset.getDouble(3));
			obj.setStatus(rset.getString(4));
			obj.setDate_time(rset.getString(5));
			objList.add(obj);
		}

	return objList;
	}

	public List<Grn> Search(Grn data) throws Exception {
		List<Grn> objList = new ArrayList<Grn>();
		con.getConnection();
		ResultSet rset = con.srh("SELECT * FROM grn WHERE grn_id = '" + data.getGrn_id()+ "'");
		while(rset.next()){
			Grn obj = new Grn();
			obj.setGrn_id(rset.getInt(1));
			obj.setSupplier_id(rset.getInt(2));
			obj.setTotal(rset.getDouble(3));
			obj.setStatus(rset.getString(4));
			obj.setDate_time(rset.getString(5));
			objList.add(obj);
		}

	return objList;
	}

}