//Generated by 24HRS
package Controllers;

import Models.Invoice;
import DataBaseConnector.Connector;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;

public class InvoiceController {

    Connector con = Connector.getInstance();

    private InvoiceController() {
    }

    private static final InvoiceController obj = new InvoiceController();

    public static InvoiceController getInstance() {
        return obj;
    }

    public void Save(Invoice data) throws Exception {
        con.getConnection();
        con.aud("INSERT INTO invoice(customer_id,total,offer_amount,status,date_time) values ('" + data.getCustomer_id() + "','" + data.getTotal() + "','" + data.getOffer_amount() + "','" + data.getStatus() + "','" + data.getDate_time() + "') ");
    }

    public void Update(Invoice data) throws Exception {
        con.getConnection();
        con.aud("UPDATE invoice SET customer_id  = '" + data.getCustomer_id() + "',total  = '" + data.getTotal() + "',offer_amount  = '" + data.getOffer_amount() + "',status  = '" + data.getStatus() + "',date_time  = '" + data.getDate_time() + "' WHERE invoice_id = '" + data.getInvoice_id() + "'");
    }

    public void Delete(Invoice data) throws Exception {
        con.getConnection();
        con.aud("DELETE FROM invoice WHERE invoice_id = '" + data.getInvoice_id() + "'");
    }

    public List<Invoice> SearchAll() throws Exception {
        List<Invoice> objList = new ArrayList<Invoice>();
        con.getConnection();
        ResultSet rset = con.srh("SELECT * FROM invoice");
        while (rset.next()) {
            Invoice obj = new Invoice();
            obj.setInvoice_id(rset.getInt(1));
            obj.setCustomer_id(rset.getInt(2));
            obj.setTotal(rset.getDouble(3));
            obj.setOffer_amount(rset.getDouble(4));
            obj.setStatus(rset.getString(5));
            obj.setDate_time(rset.getString(6));
            objList.add(obj);
        }

        return objList;
    }

    public List<Invoice> Search(Invoice data) throws Exception {
        List<Invoice> objList = new ArrayList<Invoice>();
        con.getConnection();
        ResultSet rset = con.srh("SELECT * FROM invoice WHERE invoice_id = '" + data.getInvoice_id() + "'");
        while (rset.next()) {
            Invoice obj = new Invoice();
            obj.setInvoice_id(rset.getInt(1));
            obj.setCustomer_id(rset.getInt(2));
            obj.setTotal(rset.getDouble(3));
            obj.setOffer_amount(rset.getDouble(4));
            obj.setStatus(rset.getString(5));
            obj.setDate_time(rset.getString(6));
            objList.add(obj);
        }

        return objList;
    }

    public int getLastID() throws Exception {
        int lastID = 0;

        con.getConnection();
        ResultSet rset = con.srh("SELECT * FROM invoice WHERE invoice_id = (SELECT MAX(invoice_id) FROM invoice)");
        if (rset.next()) {
            lastID = rset.getInt(1);
        }
        return lastID;
    }

}
