//Generated by 24HRS
package Controllers;

import Models.Item_registration;
import DataBaseConnector.Connector;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;

public class Item_registrationController {

    Connector con = Connector.getInstance();

    private Item_registrationController() {
    }

    private static final Item_registrationController obj = new Item_registrationController();

    public static Item_registrationController getInstance() {
        return obj;
    }

    public void Save(Item_registration data) throws Exception {
        con.getConnection();
        con.aud("INSERT INTO item_registration(name,category,description,unit_price,date_time) values ('" + data.getName() + "','" + data.getCategory() + "','" + data.getDescription() + "','" + data.getUnit_price() + "','" + data.getDate_time() + "') ");
    }

    public void Update(Item_registration data) throws Exception {
        con.getConnection();
        con.aud("UPDATE item_registration SET name  = '" + data.getName() + "',category  = '" + data.getCategory() + "',description  = '" + data.getDescription() + "',unit_price  = '" + data.getUnit_price() + "',date_time  = '" + data.getDate_time() + "' WHERE item_registration_id = '" + data.getItem_registration_id() + "'");
    }

    public void Delete(Item_registration data) throws Exception {
        con.getConnection();
        con.aud("DELETE FROM item_registration WHERE item_registration_id = '" + data.getItem_registration_id() + "'");
    }

    public double GetUnitPrice(int id) throws Exception {
        double unitPrice = 0;

        con.getConnection();
        ResultSet rset = con.srh("SELECT * FROM item_registration WHERE item_registration_id = '" + id + "' ");

        if (rset.next()) {
            unitPrice = rset.getDouble(5);
        }

        return unitPrice;
    }

    public List<Item_registration> SearchAll() throws Exception {
        List<Item_registration> objList = new ArrayList<Item_registration>();
        con.getConnection();
        ResultSet rset = con.srh("SELECT * FROM item_registration");
        while (rset.next()) {
            Item_registration obj = new Item_registration();
            obj.setItem_registration_id(rset.getInt(1));
            obj.setName(rset.getString(2));
            obj.setCategory(rset.getString(3));
            obj.setDescription(rset.getString(4));
            obj.setUnit_price(rset.getDouble(5));
            obj.setDate_time(rset.getString(6));
            objList.add(obj);
        }

        return objList;
    }

    public List<Item_registration> Search(Item_registration data) throws Exception {
        List<Item_registration> objList = new ArrayList<Item_registration>();
        con.getConnection();
        ResultSet rset = con.srh("SELECT * FROM item_registration WHERE item_registration_id = '" + data.getItem_registration_id() + "'");
        while (rset.next()) {
            Item_registration obj = new Item_registration();
            obj.setItem_registration_id(rset.getInt(1));
            obj.setName(rset.getString(2));
            obj.setCategory(rset.getString(3));
            obj.setDescription(rset.getString(4));
            obj.setUnit_price(rset.getDouble(5));
            obj.setDate_time(rset.getString(6));
            objList.add(obj);
        }

        return objList;
    }

    public double getPrice(int itemID) throws Exception {
        double price = 0;
        con.getConnection();
        ResultSet rset = con.srh("SELECT * FROM item_registration WHERE item_registration_id = '" + itemID + "'");

        if (rset.next()) {
            price = rset.getDouble(5);
        }

        return price;
    }
    
    public int getLastID() throws Exception {
        int lastID = 0;

        con.getConnection();
        ResultSet rset = con.srh("SELECT * FROM item_registration WHERE item_registration_id = (SELECT MAX(item_registration_id) FROM item_registration)");
        if (rset.next()) {
            lastID = rset.getInt(1);
        }
        return lastID;
    }

}
