//Generated by 24HRS
package Controllers;


import Models.Salary_shedule;
import DataBaseConnector.Connector;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;


public class Salary_sheduleController{

	Connector con = Connector.getInstance();

	private Salary_sheduleController(){
	}

	private static final Salary_sheduleController obj = new Salary_sheduleController();

	public static Salary_sheduleController getInstance(){
		return obj;
	}

	public void Save(Salary_shedule data) throws Exception {
		con.getConnection();
		con.aud("INSERT INTO salary_shedule(emp_id,basic_salary,ot_rate,bonus,date_time) values ('" + data.getEmp_id()+ "','" + data.getBasic_salary()+ "','" + data.getOt_rate()+ "','" + data.getBonus()+ "','" + data.getDate_time()+ "') " );
	}

	public void Update(Salary_shedule data) throws Exception {
		con.getConnection();
		con.aud("UPDATE salary_shedule SET emp_id  = '" + data.getEmp_id()+ "',basic_salary  = '" + data.getBasic_salary()+ "',ot_rate  = '" + data.getOt_rate()+ "',bonus  = '" + data.getBonus()+ "',date_time  = '" + data.getDate_time()+ "' WHERE salary_shedule_id = '" + data.getSalary_shedule_id()+ "'");
	}

	public void Delete(Salary_shedule data) throws Exception {
		con.getConnection();
		con.aud("DELETE FROM salary_shedule WHERE salary_shedule_id = '" + data.getSalary_shedule_id()+ "'");
	}

	public List<Salary_shedule> SearchAll() throws Exception {
		List<Salary_shedule> objList = new ArrayList<Salary_shedule>();
		con.getConnection();
		ResultSet rset = con.srh("SELECT * FROM salary_shedule");
		while(rset.next()){
			Salary_shedule obj = new Salary_shedule();
			obj.setSalary_shedule_id(rset.getInt(1));
			obj.setEmp_id(rset.getInt(2));
			obj.setBasic_salary(rset.getDouble(3));
			obj.setOt_rate(rset.getDouble(4));
			obj.setBonus(rset.getDouble(5));
			obj.setDate_time(rset.getString(6));
			objList.add(obj);
		}

	return objList;
	}

	public List<Salary_shedule> Search(Salary_shedule data) throws Exception {
		List<Salary_shedule> objList = new ArrayList<Salary_shedule>();
		con.getConnection();
		ResultSet rset = con.srh("SELECT * FROM salary_shedule WHERE salary_shedule_id = '" + data.getSalary_shedule_id()+ "'");
		while(rset.next()){
			Salary_shedule obj = new Salary_shedule();
			obj.setSalary_shedule_id(rset.getInt(1));
			obj.setEmp_id(rset.getInt(2));
			obj.setBasic_salary(rset.getDouble(3));
			obj.setOt_rate(rset.getDouble(4));
			obj.setBonus(rset.getDouble(5));
			obj.setDate_time(rset.getString(6));
			objList.add(obj);
		}

	return objList;
	}

}