//Generated by 24HRS
package Controllers;

import Models.Stock;
import DataBaseConnector.Connector;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;

public class StockController {

    Connector con = Connector.getInstance();

    private StockController() {
    }

    private static final StockController obj = new StockController();

    public static StockController getInstance() {
        return obj;
    }

    public void Save(Stock data) throws Exception {
        con.getConnection();
        con.aud("INSERT INTO stock(item_registration_id,qty,offer_presentage,date_time) values ('" + data.getItem_registration_id() + "','" + data.getQty() + "','" + data.getOffer_presentage() + "','" + data.getDate_time() + "') ");
    }

    public void Update(Stock data) throws Exception {
        con.getConnection();
        con.aud("UPDATE stock SET item_registration_id  = '" + data.getItem_registration_id() + "',qty  = '" + data.getQty() + "',offer_presentage  = '" + data.getOffer_presentage() + "',date_time  = '" + data.getDate_time() + "' WHERE stock_id = '" + data.getStock_id() + "'");
    }

    public void Delete(Stock data) throws Exception {
        con.getConnection();
        con.aud("DELETE FROM stock WHERE stock_id = '" + data.getStock_id() + "'");
    }

    public List<Stock> SearchAll() throws Exception {
        List<Stock> objList = new ArrayList<Stock>();
        con.getConnection();
        ResultSet rset = con.srh("SELECT * FROM stock");
        while (rset.next()) {
            Stock obj = new Stock();
            obj.setStock_id(rset.getInt(1));
            obj.setItem_registration_id(rset.getInt(2));
            obj.setQty(rset.getDouble(3));
            obj.setOffer_presentage(rset.getDouble(4));
            obj.setDate_time(rset.getString(5));
            objList.add(obj);
        }

        return objList;
    }

    public List<Stock> Search(Stock data) throws Exception {
        List<Stock> objList = new ArrayList<Stock>();
        con.getConnection();
        ResultSet rset = con.srh("SELECT * FROM stock WHERE stock_id = '" + data.getStock_id() + "'");
        while (rset.next()) {
            Stock obj = new Stock();
            obj.setStock_id(rset.getInt(1));
            obj.setItem_registration_id(rset.getInt(2));
            obj.setQty(rset.getDouble(3));
            obj.setOffer_presentage(rset.getDouble(4));
            obj.setDate_time(rset.getString(5));
            objList.add(obj);
        }

        return objList;
    }

    public int getStockIDbyItemId(int id) throws Exception {
        int stockID = 0;

        con.getConnection();
        ResultSet rset = con.srh("SELECT * FROM stock WHERE item_registration_id = '" + id + "'");
        if (rset.next()) {
            stockID = rset.getInt(1);
        }

        return stockID;
    }

    public void updateStock(int id, double qty) throws Exception {
        con.getConnection();
        con.aud("update stock set qty = qty + '" + qty + "' WHERE stock_id = '" + id + "'");
    }

}
